# Dubbo 全局配置
dubbo:
  application:
    name: dd-openapi-apiserver-web
    qos-enable: false  # 关闭QoS控制台
  registry:
    address: nacos://43.136.170.102:8848
    parameters:
      namespace: DEV
    timeout: 40000
  protocol:
    name: dubbo # 默认值就是dubbo
    port: 20883
  provider:
    timeout: 5000
  consumer:
    timeout: 5000
    check: false  # 启动时不检查提供者是否可用