############################################# server ###########################################
server:
  port: 18012
  servlet:
    context-path: /dd-openapi-apiserver-web
############################################# spring ###########################################
spring:
  application:
    name: dd-openapi-apiserver-web
  # datasource:
  #   url: jdbc:mysql://localhost:3306/dd_openapi?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  #   username: root
  #   password: root
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  ######################################## mvc ###################################
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Dubbo 全局配置
dubbo:
  application:
    name: dd-openapi-apiserver-web
    qos-enable: false  # 关闭QoS控制台
  registry:
    address: nacos://43.136.170.102:8848
    parameters:
      namespace: DEV
    timeout: 40000
  protocol:
    name: dubbo # 默认值就是dubbo
    port: 20883
  provider:
    timeout: 10000
  consumer:
    timeout: 10000
    check: false  # 启动时不检查提供者是否可用