############################################# server ###########################################
server:
  port: 18012
  servlet:
    context-path: /dd-openapi-apiserver-web
############################################# spring ###########################################
spring:
  sleuth:
    sampler:
      probability: 1.0  # 设置采样率为100%，即所有请求都会被追踪
  zipkin:
    base-url: http://47.108.200.157:9411  # Zipkin 服务的地址
    sender:
      type: web  # 设置数据传输方式为HTTP
  application:
    name: dd-openapi-apiserver-web
  ######################################## mvc ###################################
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Dubbo 全局配置
dubbo:
  application:
    name: dd-openapi-apiserver-web
    qos-enable: false  # 关闭QoS控制台
  registry:
    address: nacos://43.136.170.102:8848
    parameters:
      namespace: DEV
    timeout: 40000
  protocol:
    name: dubbo # 默认值就是dubbo
    port: 20883
  provider:
    timeout: 10000
  consumer:
    timeout: 10000
    check: false  # 启动时不检查提供者是否可用

management:
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        pushgateway:
          #job定义名
          job: ${spring.application.name}
          enabled: true
          baseUrl: http://43.136.170.102:9091
          pushRate: 15s