############################################# server ###########################################
# 以server开头的配置通常是用来配置SpringBoot应用的Web服务器相关的属性
# 这些配置由SpringBoot自动配置的嵌入式Web服务器Tomcat使用
################################################################################################
server:
  port: 10088
  servlet:
    context-path: /
######################################### SpringCloud Gateway ##########################################
# Gateway
spring:
  cloud:
    gateway:
      #####################################################################################################
      # TODO 根据目前的架构设计 路由的转发应该只有两个模块的配置 一个是用户权限模块 一个是openapi-main主模块
      routes:
        #################################### Spring Security OAuth2.0 ######################################
        # 权限转发
        - id: dd-openapi-auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**  # 权限请求转发
            - Path=/user/**
        ########################################### 服务消费转发 #############################################
        # 服务消费转发 lb://dd-openapi-main-web: lb表示使用负载均衡 dd-ms-consumer是服务名
        - id: dd-openapi-main-web-route
          uri: lb://dd-openapi-main-web  #
          predicates:
          # 匹配以 /consumer/ 开头的请求
            - Path=/csmrapi/consumer/**
          filters:
          # 去掉请求路径中的第一个前缀，例如 /service1/hello 会变成 /hello 转发到目标服务
            - StripPrefix=1
